"""empty message

Revision ID: 563bb3d060c2
Revises: 6cc570b779eb
Create Date: 2023-07-30 23:05:23.116936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563bb3d060c2'
down_revision = '6cc570b779eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Division', sa.Column('alias', sa.String(length=16), nullable=True))
    op.add_column('Division', sa.Column('name', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Division', 'name')
    op.drop_column('Division', 'alias')
    # ### end Alembic commands ###
