"""empty message

Revision ID: 66a656556f00
Revises: 563bb3d060c2
Create Date: 2023-07-30 23:07:43.911411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a656556f00'
down_revision = '563bb3d060c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
